apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: timetracking
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/nikolaev13nik/Attendance-TimeTracking.git
    targetRevision: main
    path: helm/timetracking

  destination:
    server: https://kubernetes.default.svc
    namespace: attendance

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
