apiVersion: v2
name: attendance-platform
description: Shared infrastructure for the Attendance system - namespace, config, Postgres, Kafka, Ingress
type: application

version: 0.1.1

appVersion: "17"
