namespace:
  create: false
  name: attendance

config:
  name: attendance-config
  database: attendance
  postgresHost: postgres
  postgresPort: "5432"
  driverClassName: org.postgresql.Driver
  jpaDialect: org.hibernate.dialect.PostgreSQLDialect
  accountingBaseUrl: http://accounting:8080
  kafkaBootstrapServers: kafka:9092

secret:
  name: attendance-secrets

postgres:
  enabled: true

  image: postgres:16-alpine
  user: postgres

  persistence:
    size: 2Gi
    storageClass: ""

  resources:
    requests:
      memory: 128Mi
      cpu: 50m
    limits:
      memory: 512Mi
      cpu: 500m

kafka:
  enabled: true

  serviceName: kafka

  image: apache/kafka:4.3.1

  heapOpts: "-Xmx768m -Xms256m"

  persistence:
    size: 2Gi
    storageClass: ""

  resources:
    requests:
      memory: 512Mi
      cpu: 200m
    limits:
      memory: 1536Mi
      cpu: 1000m

ingress:
  enabled: true
  className: traefik
  host: attendance.local
  annotations: {}

  paths:
    - path: /account
      service: accounting
      port: 8080
    - path: /attendance
      service: timetracking
      port: 8080
