namespace:
  create: false

config:
  postgresHost: attendance-db.abc123xyz.eu-west-1.rds.amazonaws.com

  kafkaBootstrapServers: "b-1.attendance.abc123.c2.kafka.eu-west-1.amazonaws.com:9096,b-2.attendance.abc123.c2.kafka.eu-west-1.amazonaws.com:9096"

postgres:
  enabled: false

kafka:
  enabled: false

ingress:
  className: alb

  host: attendance.example.com

  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
